spring.application.name=whatsapp-tally-integration
server.port=8080



# Tally API
tally.url=http://localhost:9000
tally.company-name=sample


whatsapp.api-url=https://graph.facebook.com/v22.0/1031084266756944/messages
whatsapp.token=EAAYeGNfZB3oMBQxaXXyFB8doRsuoO1xjvnCNPE7wpfIfvTf1hXiiDM9PEqwE7fiGVkx5PYKfBDjmVQp7SepkdccwNG956ZBFMv23QKoHesMKsw6BZApixR1oKknn9MKj9et4TUIwGxdtZBcjhmdrzdaALZCStcDDZA7Pso9V1P5tNKosm8nFUGDZAe9YoO4f2e11czHiq9lkGg3vgdKvVPoGfOORLQUhS7M0ne4AGM3l8pFZBit1NlIMQUCyVODHWbl6eHYOmuYpff4FeBQlArd6
whatsapp.phone-id=1031084266756944

whatsapp.verify-token=myWebhookToken123