spring.application.name=whatsapp-tally-integration
server.port=8080



# Tally API
tally.url=http://localhost:9000
tally.company-name=sample


whatsapp.api-url=https://graph.facebook.com/v22.0/1031084266756944/messages
whatsapp.token=EAAYeGNfZB3oMBQ1NA8PtdznhtCz2YlCFbBP16ERk3ZAB8BwKjkqnuo6ATNf58kx5dUJGpI0A7HOfErTARoNzZCjn2tsZCZAzX3XwkRTfnFX1xlKjO06cD3crvXg8e6eodqT4FDdVVZBvWCqoGtLdRZCWQyYXipAAFlhcHoT7opJ8hbIfxJXvr6ZBrgJMpYV269zIu69H6vZCXllLEGn02Db7wNXNHQQy2ITfH52At6EEMViMFloQwGqIm9mG0jxZB3CPHWQybKvsy9L56qS0dbZATNH
whatsapp.phone-id=1031084266756944

whatsapp.verify-token=myWebhookToken123