spring.application.name=whatsapp-tally-integration
server.port=8080



# Tally API
tally.url=http://localhost:9000
tally.company-name=sample


whatsapp.api-url=https://graph.facebook.com/v22.0/1031084266756944/messages
whatsapp.token=EAAYeGNfZB3oMBQZBuKtH9AFimQmEZAsxaRwvE62xwvfNhQ3YcQ1ouRj4mkvsAi6dwoSmUut4d9LEYIcz9Runqyg356QTZA5ATFJimZArikqhQwOn8c7OsKDCkQIFFgSI47r3Q6siibkZBuNTAXLrkMSnKhowvmydMfiwgERgdpc0gLJeAYS2cCso1HDMGpGCiKA4K2I4u99ZCr8sdHHUeqoHFZB9yc5cUaZAZAxErxH1z7fCU7EspOfXGv1MRI5yK4UffqsKsfIPvkCMdUcC4uLOTw
whatsapp.phone-id=1031084266756944

whatsapp.verify-token=myWebhookToken123